### ISSUE TITLE
Release Pillow 4.3.0 on October 1, 2017

### ISSUE THREAD

**Issue by homm** [python-pillow/Pillow#2664]

**Comment by homm** [comment]
In this release I'm going to work on performance of most common operations. While [Pillow-SIMD is the fastest library](https://blog.uploadcare.com/the-fastest-production-ready-image-resize-out-there-part-0-7c974d520ad9) for image convolutional resize on CPU, there is still a room for optimizations without using SIMD.

- [ ] #2655 Fast image allocation affects almost every operation. Most of them does not require expensive computations and limited only by memory bandwidth, especially with multithreading
- [ ] #2661 New `Image.getchannel()` method returns single band from image, which is common operation, especially for alpha channel
- [ ] #1989 Using RGBX rawmode for JPEG image loading and saving eliminates unnecessary color conversion for most common image format
- [ ] Methods `image.split()` and `Image.merge()` use several calls of low-level functions `im.getband()` and `im.putband()` which is not effective enough. We need specific low-level functions for this operations which will be 2-2.5 times faster.
- [ ] All filters from `ImageFilter.py` module are single channel. They are applied to multichannel images by splitting original image to bands, applying filter to each band and merging bands again. Applying filters in one pass should be much more effective. This also unlocks SIMD optimizations.
- [ ] Many functions in `Pack.c` and `Unpack.c` operate byte-by-byte (for example `ImagingUnpackRGB`). This should be more effective to read 4 bytes at once, apply transformation and write back 4 bytes. The same should be much much more effective using 128-bit SIMD registers.

I also worried about [VIPS benchmarks](https://github.com/jcupitt/libvips/wiki/Speed-and-memory-use). Pillow doesn't show good result, because ≈70% of execution time is the filter applying (which is one of the most ineffective operation in Pillow). Funny thing is according to my tests Pillow is **already faster** than Python-VIPS in concurrent mode on 4-cores, even with such ineffective filters. My aim to next release is to make Pillow-SIMD on **single core** as fast as Python-VIPS on **all 6 cores** of Xeon E5-1650, used for tests :-> I also want to add VIPS benchmarks to [pillow-perf](https://github.com/python-pillow/pillow-perf) despite the fact that Python-VIPS is very hard to install.

**Comment by wiredfool** [comment]
Sounds good to me.  I'm still mostly away from the keyboard for a few more days, but I'm hoping to have a chance to go through these prs within a week or so.

**Comment by wiredfool** [comment]
* [ ] release notes for #2699

**Comment by homm** [comment]
Things nice to have:

* Autorotate for JPEG and TIFF images based on EXIF. (Very likely, especially with #2730)
* Deprecate undocumented functions in the end of `ImageOps` module in favor of `ImageFilter` (also likely)
* Check changed core functions and possible other for the GIL releasing
* Check is it still possible to finish #1122

**Comment by aclark4life** [comment]
Thanks @homm for creating this ticket. 👍  (Time for quarterly ritual of toggling Not Watching to Watching.) 

<img width="337" alt="screenshot 2017-09-27 11 49 27" src="https://user-images.githubusercontent.com/72164/30923504-06cf68b0-a37a-11e7-9e72-20aeb438cd4f.png">

**Comment by jbltx** [comment]
Thank you @wiredfool for your work on #2769, i didn't find the time to finish it so i'm glad someone was here for that.

**Comment by wiredfool** [comment]
@jbltx You're welcome.

**Comment by aclark4life** [comment]
@python-pillow/pillow-team Should we move this release to Oct 2 or 3?

**Comment by cgohlke** [comment]
I think https://github.com/python-pillow/Pillow/issues/2772 is a release blocker.

**Comment by wiredfool** [comment]
release notes for #2769

**Comment by radarhere** [comment]
For anyone just reading this thread, #2772 has been resolved.

**Comment by wiredfool** [comment]
I think we're pretty nearly done here. 

* Either #2778 or #2775 is going to go in, and that's the end of the code changes. 
* There are still some docs that I want to work on, but that can happen after the check run for linux/osx wheels.
* I'm going to push #1122 and #2761 back, hopefully merge #2761 in the next week or so, and then untangle #1122 into that as well.

**Comment by wiredfool** [comment]
I've tagged release 4.3.0: https://github.com/python-pillow/Pillow/tree/4.3.0

Linux wheels are done, one OSX build to go.

**Comment by cgohlke** [comment]
Windows binaries are at http://www.lfd.uci.edu/~gohlke/download/Pillow-4.3.0-win-dist.zip

**Comment by jbltx** [comment]
@cgohlke What is the delay to get this from pip ?

**Comment by wiredfool** [comment]
I'm going to upload them shortly

**Comment by wiredfool** [comment]
Ok, they're uploaded. Thanks for the binaries @cgohlke.

**Comment by aclark4life** [comment]
Thanks all!

**Comment by hugovk** [comment]
* [x] Announce release availability via Twitter: https://twitter.com/PythonPillow/status/915244121677340673

**Comment by paulopires16** [comment]
RGB to PALETTE conversion
I'm trying to convert RGB image to PALETTE image with PIL: 

```
img = Image.open(tiffile) 
img = img1convert("P", palette=Image.ADAPTIVE, colors=256) 
img.save(newtiffile+"_index.tif")     
img.close()
```

...but, for example, the white color is 245, not 255 :( 
And from CMYK to PALETTE? Is it possible?
Thanks

**Comment by wiredfool** [comment]
@paulopires16 Please don't hijack old unrelated threads. 

Since it's a palette image, there's no guarantee that any specific color will appear, or where the colors appear in the palette.
