### ISSUE TITLE
Add support for Python 3.9

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#4953]
Tracking issue for getting the pieces into place to support Python 3.9 in Pillow 8.0.0, [scheduled for 2020-10-15](https://github.com/python-pillow/Pillow/issues/4764).

* [x] Wait for 3.9.0: https://discuss.python.org/t/python-3-9-0-is-now-available-and-you-can-already-test-3-10-0a1/5375?u=hugovk
* [x] Wait for 3.9 on GHA: https://github.com/actions/setup-python/issues/148#issuecomment-704287600
* [x] Wait for 3.9 on Travis CI: https://travis-ci.community/t/python-3-9-0-build/10091?u=hugovk
* [x] Wait for 3.9 on AppVeyor: https://github.com/appveyor/ci/issues/3541
* [x] #4951 Replace `3.9-dev` with `3.9` on GHA
* [x] #5010 Replace `3.9-dev` with `3.9` on Travis CI
* [x] #5014 Replace `3.8` with `3.9` on AppVeyor
* [x] #4952 Add Trove classifier, update `setup.py` version check, add to `tox.ini`
* [x] Update support table https://pillow.readthedocs.io/en/latest/installation.html#platform-support
* [x] #4961 Update CI targets https://pillow.readthedocs.io/en/latest/installation.html#continuous-integration-targets
* [x] https://github.com/python-pillow/pillow-wheels/pull/164 Update https://github.com/python-pillow/pillow-wheels

**Comment by evandrix** [comment]
[Pillow-7.2.0-cp39-cp39-win_amd64.whl.zip](https://github.com/python-pillow/Pillow/files/5360592/Pillow-7.2.0-cp39-cp39-win_amd64.whl.zip)

**Comment by cclauss** [comment]
`3.9-dev` on Travis CI is currently installing Python 3.9.0+

**Comment by hugovk** [comment]
Yep, on Travis `-dev` is a daily build from the corresponding branch.

(On GHA, `-dev` is the last tagged release.)

Looks like we have the minimum in place for the release.

**Comment by ci4ic4** [comment]
> [Pillow-7.2.0-cp39-cp39-win_amd64.whl.zip](https://github.com/python-pillow/Pillow/files/5360592/Pillow-7.2.0-cp39-cp39-win_amd64.whl.zip)

Worked just fine for me as well.

**Comment by hugovk** [comment]
Pillow 8.0.0 is now out supporting Python 3.9!

https://github.com/python-pillow/Pillow/issues/4764#issuecomment-708581326

Let's keep this open to track the last couple of CIs.
