### ISSUE TITLE
Add support for Python 3.10

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#5569]
Tracking issue for getting the pieces into place to support Python 3.10 in Pillow 8.4.0, scheduled for 2020-10-15.

* [x] Wait for 3.10.0, expected [Monday, 2021-10-04](https://www.python.org/dev/peps/pep-0619/)
* [x] Wait for 3.10.0 on GHA: https://github.com/actions/setup-python/issues/249
* [x] Wait for 3.10.0 on AppVeyor: https://github.com/appveyor/ci/issues/3741
* [ ] Wait for 3.10.0 on Travis CI (https://github.com/python-pillow/pillow-wheels): https://travis-ci.community/t/add-python-3-10/12220
* [x] ([#5748](https://github.com/python-pillow/Pillow/pull/5748)) Replace `3.10-dev` with `3.10` on GHA
* [x] ([#5805](https://github.com/python-pillow/Pillow/pull/5805)) Replace `3.9` with `3.10` on AppVeyor
* [x] ([#5570](https://github.com/python-pillow/Pillow/pull/5570)) Add Trove classifier, update `setup.py` version check, add to `tox.ini`, update [Python support table](https://pillow.readthedocs.io/en/stable/installation.html#python-support)
* [x] ([#5713](https://github.com/python-pillow/Pillow/pull/5713)) Update [CI targets table](https://pillow.readthedocs.io/en/latest/installation.html#continuous-integration-targets)
* [x] ([python-pillow/pillow-wheels#215](https://github.com/python-pillow/pillow-wheels/pull/215) [python-pillow/pillow-wheels#217](https://github.com/python-pillow/pillow-wheels/pull/217)) Update https://github.com/python-pillow/pillow-wheels

(3.9 issue for comparison: https://github.com/python-pillow/Pillow/issues/4953)

**Comment by wiredfool** [comment]
I've seen this mentioned elsewhere and it makes sense -- Shipping a py 3.10 compatible/tagged wheel before the actual release can help with other libraries sorting their compatibility. It could reduce the support load here as well, as we wouldn't get the confusion from people attempting to compile for 3.10 in the window between it coming out and us (well, you) getting the new release out. This assumes that we can run the RC in the testing setup, and I'm not 100% clear that that's actually the case. 

In the unlikely event that the 3.10 RC differs from 3.10 final in a significant manner, we can roll a point release.

**Comment by hugovk** [comment]
We have an 11 day buffer between 3.10.0 final release and Pillow release, and I was going to suggest doing the Pillow release as soon as we're actually ready, before the end of that buffer.

But yes, sounds good to put out RC wheels first. We've already been testing this repo against 3.10 on GHA. 

What do we need?

# Windows

https://www.lfd.uci.edu/~gohlke/pythonlibs/#pillow already has 3.10 wheels for the newest Pillow 8.3.1, so we could upload those right away (or first check/ask for a build against RC1).

# macOS and Linux

Update https://github.com/python-pillow/pillow-wheels for 3.10, first we need https://github.com/matthew-brett/multibuild to add support?

multibuild depends on https://github.com/pypa/manylinux which already supports 3.10.0 RC1: https://github.com/pypa/manylinux/pull/1159.

**Comment by nulano** [comment]
#5651 fixing the FriBiDi segmentation fault would probably be good to include in a point release also.

**Comment by hugovk** [comment]
Yep, looks a good candidate for inclusion too, if no objections from others.

I'll put together release notes and I can make a 8.3.2 release this week.

**Comment by hugovk** [comment]
:rocket: Pillow 8.3.2 with Python 3.10 wheels released:

* https://pillow.readthedocs.io/en/stable/releasenotes/8.3.2.html
* https://pypi.org/project/Pillow/8.3.2/#files

**Comment by hugovk** [comment]
Update on 3.10 for the CIs. In short: no release blockers.

* GitHub Actions: had 3.10 available 12 hours after release. 🥇 

* AppVeyor: https://github.com/appveyor/ci/issues/3741 is in their next-images-update milestone, no ETA, 36% complete. I'm not worried if we don't have this for Friday's release: it's for testing, we're already testing 3.10 on GHA, and we already released 8.3.2 for 3.10 with no issues.

* Travis CI: no reaction at all from Travis to the request: https://travis-ci.community/t/add-python-3-10/12220. I'm even less worried about this, we use Docker to create those wheels (including 3.10) so it doesn't really matter what Python is on the Travis machine (and `3.10-dev` is available).

**Comment by hugovk** [comment]
Update:

AppVeyor now has 3.10 available: https://github.com/python-pillow/Pillow/pull/5805.

Still no response from Travis CI whatsoever: https://travis-ci.community/t/add-python-3-10/12220.

**Comment by hugovk** [comment]
> * Travis CI: no reaction at all from Travis to the request: [travis-ci.community/t/add-python-3-10/12220](https://travis-ci.community/t/add-python-3-10/12220). I'm even less worried about this, we use Docker to create those wheels (including 3.10) so it doesn't really matter what Python is on the Travis machine (and `3.10-dev` is available).

Let's close this issue now, it doesn't matter when we change the Travis version (but ideally before 3.9's EOL in 2025!).

https://github.com/python-pillow/pillow-wheels/blob/706f721b23c02b0d04061c33521562e41dc0f053/.travis.yml#L12
