### ISSUE TITLE
Add support for Python 3.11

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#6575]
Tracking issue for getting the pieces into place to support Python 3.11 in Pillow 9.3.0, released on 2022-10-24.

* [x] Wait for 3.11.0, expected [Monday, 2022-10-24](https://peps.python.org/pep-0664/)
* [x] Update https://github.com/python-pillow/pillow-wheels
  * [x] macOS: https://github.com/python-pillow/pillow-wheels/pull/336
  * [x] manylinux: https://github.com/pypa/manylinux/issues/1317, https://github.com/python-pillow/pillow-wheels/pull/337
* [x] ([#6441](https://github.com/python-pillow/Pillow/pull/6441), [#6433](https://github.com/python-pillow/Pillow/pull/6433)) Add Trove classifier, update `setup.py` version check, add to `tox.ini`, update [Python support table](https://pillow.readthedocs.io/en/stable/installation.html#python-support)
* [x] Update [CI targets table](https://pillow.readthedocs.io/en/latest/installation.html#continuous-integration-targets)

# Non-blockers

* [x] Wait for 3.11.0 on GHA: https://github.com/actions/setup-python/issues/531
  * [x] Replace `3.11-dev` with `3.11` on GHA: https://github.com/python-pillow/Pillow/pull/6686
  * `3.11-dev` should pick up 3.11.0 on-flight fairly soon after release, and be added to cached images later
* [x] Wait for 3.11.0 on AppVeyor: https://github.com/appveyor/ci/issues/3844
  * [x] Replace `3.10` with `3.11` on AppVeyor: https://github.com/python-pillow/Pillow/pull/6723
* [ ] Wait for 3.11.0 on Travis CI (https://github.com/python-pillow/pillow-wheels): https://travis-ci.community/t/please-add-image-for-python-3-11/13384
  * this is base Python, we use Docker for building wheels 

(3.10 issue for comparison: https://github.com/python-pillow/Pillow/issues/5569)

**Comment by hugovk** [comment]
* Does "Update https://github.com/python-pillow/pillow-wheels" have any external dependencies, other than the 3.11.0 release itself? Can we do things like https://github.com/python-pillow/pillow-wheels/pull/324 so we don't need to wait for multibuild updates?

* Is "Wait for 3.11.0 on AppVeyor" also a non-blocker? We're already testing 3.11 quite widely on Windows on GitHub Actions.

**Comment by radarhere** [comment]
> * Does "Update https://github.com/python-pillow/pillow-wheels" have any external dependencies, other than the 3.11.0 release itself? Can we do things like [Updated Python 3.11 to rc2 pillow-wheels#324](https://github.com/python-pillow/pillow-wheels/pull/324) so we don't need to wait for multibuild updates?

[pillow-wheels#324](https://github.com/python-pillow/pillow-wheels/pull/324) updates the macOS Python version so that we don't need to wait for multibuild, yes. The Linux Python versions though, come from images like https://quay.io/repository/pypa/manylinux_2_28_x86_64,

**Comment by hugovk** [comment]
Good stuff, and those images are published by https://github.com/pypa/manylinux/ who should be quick about updating. (And it looks like they have automation too.)

**Comment by nulano** [comment]
> Is "Wait for 3.11.0 on AppVeyor" also a non-blocker? We're already testing 3.11 quite widely on Windows on GitHub Actions.

Yes. AppVeyor is used as both a backup in case GHA stops working, as well as to make sure the Windows builds are not specific to GHA and can be done elsewhere also.

**Comment by hugovk** [comment]
Main thing we're missing here is manylinux updating from 3.11.0rc2 to 3.11.0 final:

For example:

* https://github.com/hugovk/pillow-wheels/actions/runs/3321491929/jobs/5489216523#step:4:6696

Tracking issue:

* https://github.com/pypa/manylinux/issues/1317

**Comment by wiredfool** [comment]
Looks like the manylinux wheel issue was closed half an hour ago.

**Comment by hugovk** [comment]
Hmm, while [linux / 3.11 manylinux2014 i686](https://github.com/python-pillow/pillow-wheels/actions/runs/3327307362/jobs/5501975204#logs) is picking up the new version:

```
  Python 3.11.0 (main, Oct 24 2022, 19:56:01) [GCC 7.5.0]
```

But [linux / 3.11 manylinux2014 x86_64](https://github.com/python-pillow/pillow-wheels/actions/runs/3327307362/jobs/5501975308#logs), 
[linux / 3.11 manylinux_2_28 x86_64](https://github.com/python-pillow/pillow-wheels/actions/runs/3327307362/jobs/5501975452#logs) and 
[linux / 3.11 musllinux_1_1 x86_64](https://github.com/python-pillow/pillow-wheels/actions/runs/3327307362/jobs/5501976119#logs) are still on RC1 (and there was also an RC2):

```
  Python 3.11.0rc1 (main, Aug  8 2022, 18:31:54) [GCC 9.4.0]
```

**Comment by radarhere** [comment]
That's because the i686 3.11 job uses [my docker test image](https://github.com/python-pillow/pillow-wheels/blob/2ee3cd2007d338627b0a248afae99852d1fc58cc/.github/workflows/build.sh#L22-L23), whereas the others don't. The wheels are being built with Python 3.11 on those other environments, just not tested on them. I've created https://github.com/python-pillow/pillow-wheels/pull/337 to fix that.

**Comment by hugovk** [comment]
https://github.com/multi-build/multibuild/pull/485, https://github.com/multi-build/docker-images/pull/37 and https://github.com/python-pillow/pillow-wheels/pull/337 are merged, so the important 3.11 things are now ready! 🚀

**Comment by radarhere** [comment]
To anyone watching this issue, Pillow 9.3.0 has now been released, so the latest wheels support Python 3.11.

**Comment by hugovk** [comment]
All the important things are in place and it could take Travis CI a long time to update (was ~3 months last time).

We can just update Travis as and when, no need to keep this open as a tracking issue.

**Comment by radarhere** [comment]
Travis CI has [updated to Python 3.11](https://travis-ci.community/t/please-add-image-for-python-3-11/13384/3), and https://github.com/python-pillow/pillow-wheels/pull/345 has added it to pillow-wheels.

So that is everything in our checklist.
