### ISSUE TITLE
Release Pillow 10.1.0 on October 15, 2023

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#7348]
Highlights:

* https://github.com/python-pillow/Pillow/issues/6941

## TODO

* [x] Merge https://github.com/python-pillow/pillow-wheels/pull/400 before release
* [x] https://github.com/python-pillow/Pillow/issues/6941

## Main Release

Released quarterly on January 2nd, April 1st, July 1st and October 15th.

* [x] Open a release ticket e.g. https://github.com/python-pillow/Pillow/issues/3154
* [x] Develop and prepare release in `main` branch.
* [x] Check [GitHub Actions](https://github.com/python-pillow/Pillow/actions) and [AppVeyor](https://ci.appveyor.com/project/python-pillow/Pillow) to confirm passing tests in `main` branch.
* [x] Check that all of the wheel builds pass the tests in the [GitHub Actions "Wheels" workflow](https://github.com/python-pillow/Pillow/actions/workflows/wheels.yml) and [Travis CI](https://app.travis-ci.com/github/python-pillow/pillow) jobs by manually triggering them.
* [x] In compliance with [PEP 440](https://peps.python.org/pep-0440/), update version identifier in `src/PIL/_version.py`
* [x] Update `CHANGES.rst`.
* [x] Run pre-release check via `make release-test` in a freshly cloned repo.
* [x] Create branch and tag for release e.g.:
  ```bash
  git branch 5.2.x
  git tag 5.2.0
  git push --tags
  ```
* [x] Create and check source distribution:
  ```bash
  make sdist
  ```
* [x] Create [binary distributions](https://github.com/python-pillow/Pillow/blob/main/RELEASING.md#binary-distributions)
* [x] Check and upload all binaries and source distributions e.g.:
  ```bash
  python3 -m twine check --strict dist/*
  python3 -m twine upload dist/Pillow-5.2.0*
  ```
* [x] Publish the [release on GitHub](https://github.com/python-pillow/Pillow/releases)
* [x] In compliance with [PEP 440](https://peps.python.org/pep-0440/),
      increment and append `.dev0` to version identifier in `src/PIL/_version.py` and then:
  ```bash
  git push --all
   ```

### macOS and Linux
* [x] Download wheels from the [GitHub Actions "Wheels" workflow](https://github.com/python-pillow/Pillow/actions/workflows/wheels.yml)
  and copy into `dist/`. For example using [GitHub CLI](https://github.com/cli/cli):
  ```bash
  gh run download --dir dist
  # select dist-x.y.z
  ```
* [x] Download the Linux aarch64 wheels created by Travis CI from [GitHub releases](https://github.com/python-pillow/Pillow/releases)
  and copy into `dist`.

### Windows
* [x] Download the artifacts from the [GitHub Actions "Test Windows" workflow](https://github.com/python-pillow/Pillow/actions/workflows/test-windows.yml)
  and copy into `dist/`. For example using [GitHub CLI](https://github.com/cli/cli):
  ```bash
  gh run download --dir dist
  # select dist-x.y.z
  ```

## Publicize Release

* [x] Announce release availability via [Twitter](https://twitter.com/pythonpillow) and [Mastodon](https://fosstodon.org/@pillow) e.g. https://twitter.com/PythonPillow/status/1013789184354603010

## Documentation

* [x] Make sure the [default version for Read the Docs](https://pillow.readthedocs.io/en/stable/) is up-to-date with the release changes

## Docker Images

* [x] Update Pillow in the Docker Images repository
  ```bash
  git clone https://github.com/python-pillow/docker-images
  cd docker-images
  ./update-pillow-tag.sh [[release tag]]
  ```

**Comment by bsekachev** [comment]
Hello, 
May I ask if you are going to include #7383 to the October Release? 
Or it is already to late, and it will be postponed till the next one?

**Comment by homm** [comment]
For the record: release is delayed from common 1st October to 15th October due to [Python 3.12 support](https://github.com/python-pillow/Pillow/issues/6941) which will be released at 15th October.

**Comment by aclark4life** [comment]
Right, and the aforementioned record on release schedule is here: https://pillow.readthedocs.io/en/stable/releasenotes/index.html#release-notes

**Comment by hugovk** [comment]
It's release day!

About PR https://github.com/python-pillow/Pillow/pull/7307. I merged it, but now I'm having second thoughts. Sorry for raising this last minute, but rather before the release. 

The release notes call it a breaking change:

> If you attempt to set the mode of an image directly, e.g. im.mode = "RGBA", you will now receive an AttributeError. This is not about removing existing functionality, but instead about raising an explicit error to prevent later consequences. The convert method is the correct way to change an image’s mode.

https://pillow.readthedocs.io/en/latest/releasenotes/10.1.0.html#backwards-incompatible-changes

We use SemVer and 10.1.0 is not a major release that would allow breaking changes.

Options:

* Is this breaking change acceptable for a minor release? If so, let's keep it. 
* We could bump to 11.0.0. We normally align major releases with a Python EOL drop, but I don't think we have anything preventing us also doing major bumps at other times. 
* Reframe the change as something other than a breaking change. A bug fix? Bug fixes do sometimes break things... See xkcd space bar heating. 
* Revert, potentially add deprecation warnings as usual (in this release or next), remove in next major release. 

@python-pillow/pillow-team Thoughts?

**Comment by radarhere** [comment]
I don't think it should be a breaking change for the normal user - I find it hard to think of a safe practical use for this, and we released #3203 for ``size`` in Pillow 5.3.0.

It is a breaking change if you are writing your own plugins for Pillow, e.g. https://github.com/bigcat88/pillow_heif/pull/122, but I don't think we consider that when creating releases.

I've created #7465 to move it to a different section of the release notes, and improve the documentation about writing your own plugin.

**Comment by hugovk** [comment]
Hmm, on the one hand, SemVer doesn't distinguish between normal users and plugins users, it's all part of the public API. But the exposure is clearly smaller, plugins do things a bit differently, and in this case it's fine to set an internal `mode_`. 

Thanks for the PR, let's go with it, and if there are other plugins we can give a heads-up to, let's do that.

**Comment by hugovk** [comment]
Travis CI build failed to upload the wheels to the GH release:

```
invalid option "--token="
failed to deploy
```

https://app.travis-ci.com/github/python-pillow/pillow/builds/266593993

**Comment by hugovk** [comment]
I think this is because the token was originally generated against the https://github.com/python-pillow/pillow-wheels/ repo:

https://github.com/python-pillow/pillow-wheels/pull/156#discussion_r450959499

So we need to update it for this https://github.com/python-pillow/Pillow repo and replace it at https://app.travis-ci.com/github/python-pillow/pillow-wheels/settings.

I'll try that.

**Comment by hugovk** [comment]
```console
❯ sudo gem install travis --no-document
...
❯ travis --version
Shell completion not installed. Would you like to install it now? |y| y
1.11.1

❯ travis setup releases
Detected repository as python-pillow/Pillow/, is this correct? |yes|
resource not found ({}
)

❯ travis login
resource not found ({}
)

```

I need to pop out for an hour or so, to be continued...

**Comment by aclark4life** [comment]
Not related to this release but wondering do we still need to Travis to build wheels? Thinking of this as potential replacement: https://github.com/pypa/cibuildwheel

**Comment by radarhere** [comment]
If you're interested in a quick fix for this release, here are aarch64 wheels. As I have sometimes before, I generated them by adjusting the Travis script to upload the wheels to https://www.file.io/

[aarch64-Python38-39.zip](https://github.com/python-pillow/Pillow/files/12909464/aarch-Python38-39.zip)
[aarch64-Python310-311.zip](https://github.com/python-pillow/Pillow/files/12909467/aarch64-Python310-311.zip)
[aarch64-Python312.zip](https://github.com/python-pillow/Pillow/files/12909468/aarch64-Python312.zip)

**Comment by hugovk** [comment]
I would very much like to move from multibuild to cibuildwheel. Both are fantastic projects, multibuild came first, and cibuildwheel learnt a lot from multibuild (see https://github.com/pypa/cibuildwheel#credits). 

We're using Travis CI to build aarch64 wheels because of the available hardware. We can already build them on GHA, but it's sloooow due to emulation. See https://github.com/python-pillow/Pillow/issues/7390.

I expect cibuildwheel would be about as slow with cibuildwheel. 

And when we the automation of https://github.com/python-pillow/Pillow/issues/7390 full in place, perhaps the slowness will be acceptable. Definitely something to evaluate when the time comes.

**Comment by hugovk** [comment]
> If you're interested in a quick fix for this release, here are aarch64 wheels. As I have sometimes before, I generated them by adjusting the Travis script to upload the wheels to https://www.file.io/
> 
> [aarch64-Python38-39.zip](https://github.com/python-pillow/Pillow/files/12909464/aarch-Python38-39.zip) [aarch64-Python310-311.zip](https://github.com/python-pillow/Pillow/files/12909467/aarch64-Python310-311.zip) [aarch64-Python312.zip](https://github.com/python-pillow/Pillow/files/12909468/aarch64-Python312.zip)

Thanks, I'll probably use those if `travis` isn't a trivially fixable!

**Comment by hugovk** [comment]
It wasn't trivially fixable, so I used those. Thanks!

Looks like we need to create a GitHub API token, then use that to login to `travis`, then create the new release token and save it as `GITHUB_RELEASE_TOKEN` at https://app.travis-ci.com/github/python-pillow/pillow-wheels/settings.

@aclark4life The GitHub token should be scoped against this repo, and I'm not an admin here so can't do that, so can I delegate this to you? :) No rush on this, and we can create a new issue for it.

**Comment by hugovk** [comment]
All released, announcements to follow soon!

* https://pypi.org/project/Pillow/10.1.0/
* https://github.com/python-pillow/Pillow/releases/tag/10.1.0
* https://pillow.readthedocs.io/en/stable/releasenotes/10.1.0.html

Thanks everyone!

**Comment by hugovk** [comment]
🚀 https://fosstodon.org/@pillow/111239876043326065

**Comment by radarhere** [comment]
Twitter announcement: https://twitter.com/PythonPillow/status/1713600484248842255

**Comment by hugovk** [comment]
> It wasn't trivially fixable, so I used those. Thanks!
> 
> Looks like we need to create a GitHub API token, then use that to login to `travis`, then create the new release token and save it as `GITHUB_RELEASE_TOKEN` at [app.travis-ci.com/github/python-pillow/pillow/settings](https://app.travis-ci.com/github/python-pillow/pillow/settings).
> 
> @aclark4life The GitHub token should be scoped against this repo, and I'm not an admin here so can't do that, so can I delegate this to you? :) No rush on this, and we can create a new issue for it.

Issue for this: https://github.com/python-pillow/Pillow/issues/7485

**Comment by radarhere** [comment]
> I would very much like to move from multibuild to cibuildwheel. Both are fantastic projects, multibuild came first, and cibuildwheel learnt a lot from multibuild (see https://github.com/pypa/cibuildwheel#credits).

Thanks to #7552, we are now using cibuildwheel.
